[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]
solc = "0.8.25"
evm_version = 'cancun'

optimizer = true
optimizer_runs = 5000

[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
avalanche_fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"
optimism = "https://optimism-rpc.publicnode.com"
optimism_sepolia = "https://optimism-sepolia-rpc.publicnode.com"
arbitrum = "https://arbitrum-rpc.publicnode.com"
arbitrum_sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
base = "https://base-rpc.publicnode.com"
base_sepolia = "https://base-sepolia-rpc.publicnode.com"
polygon = "https://polygon-bor-rpc.publicnode.com"
polygon_amoy = "https://polygon-amoy-bor-rpc.publicnode.com"

[etherscan]
mainnet = { key = "${ETH_BLOCK_EXPLORER_API_KEY}" }
sepolia = { key = "${ETH_BLOCK_EXPLORER_API_KEY}" }
avalanche = { key = "${AVAX_BLOCK_EXPLORER_API_KEY}" }
avalanche_fuji = { key = "${AVAX_BLOCK_EXPLORER_API_KEY}" }
optimism = { key = "${OP_BLOCK_EXPLORER_API_KEY}" }
optimism_sepolia = { key = "${OP_BLOCK_EXPLORER_API_KEY}" }
arbitrum = { key = "${ARBITRUM_BLOCK_EXPLORER_API_KEY}" }
arbitrum_sepolia = { key = "${ARBITRUM_BLOCK_EXPLORER_API_KEY}" }
base = { key = "${BASE_BLOCK_EXPLORER_API_KEY}" }
base_sepolia = { key = "${BASE_BLOCK_EXPLORER_API_KEY}" }
polygon = { key = "${POLYGON_BLOCK_EXPLORER_API_KEY}" }
polygon_amoy = { key = "${POLYGON_BLOCK_EXPLORER_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
