[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]
solc = "0.8.25"
evm_version = 'cancun'

optimizer = true
optimizer_runs = 5000

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
optimism_sepolia = "https://sepolia.optimism.io"

[etherscan]
base = { key = "${BASE_BLOCK_EXPLORER_API_KEY}" }
base_sepolia = { key = "${BASE_BLOCK_EXPLORER_API_KEY}" }
optimism_sepolia = { key = "${OP_BLOCK_EXPLORER_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
